# Generated by Django 5.2.5 on 2025-09-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SatelliteImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="satellite/")),
                ("upload_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
